### ISSUE TITLE
Deploying Cartridge app to multiple k8s clusters

### ISSUE THREAD

**Issue by vanyarock01** [tarantool/tarantool-operator#110]
Tarantool-operator does not support working with multiple k8s clusters. It is necessary to research the possibility of deploying and managing a Cartridge app in multiple k8s clusters.

The complexity of the task lies in the fact that two different k8s clusters are two different systems (etcd, kube-api, etc.), which must be connected so that the topology of a single cartridge application remains correct and flexible.

_Correctness_ means that tarantool nodes from different k8s clusters will be connected in the same way as nodes of one k8s cluster, and there will also be no duplicate instances/replicasets in different k8s clusters.
_Flexibility_ means support for correct scaling of a cartridge application.

The solution must support the main features of the tarantool-operator:
- Correctly deploy a cartridge app to multiple K8S clusters
- Manage the topology of the cartridge cluster (scaling replicas and replicasets)
- Rolling upgrade (would be very nice)

One of the possible approaches to the solution could be using kubefed.

**Comment by kluevandrew** [comment]
Won't fix in community edition
