### ISSUE TITLE
Reconciling Cluster every 5 sec

### ISSUE THREAD

**Issue by nekufa** [tarantool/tarantool-operator#114]
We have simplest cartridge application that uses only built-in roles:
- vshard-router, vshard-storage
- crud-router, crud-storage
- migrator
- metrics

This application is deployed to kubernetes using standard tarantool-operator helm.
Everything looks okay, but every 5 seconds there are a lot of log messages about cluster reconcilling.

I collect all needed data at public gist page here:
https://gist.github.com/nekufa/bcf619ec14294211ad3d7ffe8eb4925b

Gist contains:
- cartridge application rockspec and init file (data-scm-1.rockspec, init.lua)
- helm values for deployment (queue-data.yaml)
- all service logs (tarantool-operator-\*.log, queue-data-instance-\*.log)

**Comment by Stomator** [comment]
+
