### ISSUE TITLE
Create helm-chart for cartridge-app deploy and publish to helm hub

### ISSUE THREAD

**Issue by vanyarock01** [tarantool/tarantool-operator#19]
You can take the chart from the [example](https://github.com/tarantool/tarantool-operator/tree/master/examples/kv/helm-chart)

**Comment by vasiliy-t** [comment]
I've setup Helm repository via github pages. There are two charts available in repo: operator char and cartridge application chart. 

Just add repo to helm:

```shell
$ helm repo add tarantool https://tarantool.github.io/tarantool-operator
``` 

You could use it now:

```shell
$ helm search repo tarantool
---
NAME                        	CHART VERSION	APP VERSION	DESCRIPTION                  
tarantool/tarantool-operator	0.0.5        	1.16.0     	kubernetes tarantool operator
tarantool/cartridge         	0.0.5        	1.0        	A Helm chart for tarantool   
```

Next step is to add reference to our repo from helm hub. 

**NOTE** Looks like helm hub is migrating it's contents to [artifact hub](https://github.com/helm/hub/issues/439)

**Comment by sharonovd** [comment]
Done
