### ISSUE TITLE
Cannot install Operator

### ISSUE THREAD

**Issue by DmitriyVTitov** [tarantool/tarantool-operator#194]
I try to follow installation documentation but the command:
```
helm install tarantool-operator-ce tarantool/tarantool-operator
```
produces error:
```
Error: INSTALLATION FAILED: chart "tarantool-operator" matching  not found in tarantool index. (try 'helm repo update'): no chart version found for tarantool-operator-
```

**Comment by kluevandrew** [comment]
From some time, helm stopped working with suffixes in versions, for example "-rc2". 
I have published the charts with new versions, please do `helm repo update` and try again
