### ISSUE TITLE
applying roles to instances hang on kubernetes version 1.25+ 

### ISSUE THREAD

**Issue by vdovinmih** [tarantool/tarantool-operator#220]
### Expected behavior
roles are applied to instances without an infinite loop.

What do you want to achieve?
correct application of roles

### Actual behavior
kubernetes versions 1.25 and higher (verified in versions 1.25, 1.26, 1.27) roles are applied to instances in infinite loop.

What is happening?
tarantool-operator applying roles to random instance in a loop. i see infinite logs in operator and cartridge instances

### Steps to reproduce the behavior
- use kubernetes versions 1.25

- Add helm repository
  ```shell
  helm repo add tarantool https://tarantool.github.io/helm-charts/
  ```
- Configure the Operator deployment (optional)
  ```shell
  helm show values tarantool/tarantool-operator > operator-values.yaml
  ```
  Edit `operator-values.yaml` file if needed, all parameters described in comments.
- Install/Update operator (choose on of)
  ```shell
  helm upgrade --install tarantool-operator-ce tarantool/tarantool-operator [--values ./operator-values.yaml]
  ```
- see logs

### Environment

How are the pieces configured?
* Tarantool Operator version: v1.0.0-rc3
* Tarantool version: 2.11.1
* Cartridge version: 2.8.2-1
* Kubernetes version: 1.25
* Helm chart configuration used: custom application with vshard-router and vshard-storage roles configured

Kubernetes version: 1.24.8 - works without a problem

**Comment by d-enk** [comment]
Tried with 1.25.15 and v1.28.7
Everything is okay
Need more info

**Comment by vdovinmih** [comment]
It is not reproducible in v1.28.7
Not sure about exact revisions 1.25, 1.26, 1.27. 

I think we can close this

**Comment by sergos** [comment]
Resolved with latest kubernetes release.
