### ISSUE TITLE
Configurable cluster_name

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/tarantool-operator#38]
### Problem statement 

We use services and dns to communicate within cluster. Instance DNS name contains kubernetes cluster_name (cluster.local) and it is hardcoded in operator. users with different cluster names will not be able to bootstrap cluster

### Possible solutions

- remove cluster name from dns name

- support configurable cluster_name (whatever we call it) in operator and charts

**Comment by vanyarock01** [comment]
To solve by configuration method:
- unhardcode `cluster.local` in operator [code](https://github.com/tarantool/tarantool-operator/blob/fe1a588f2ecdacfb8f6a5833b1611011fdd8a6d5/pkg/topology/builtin.go#L194)
- unhardcode `cluster.local` in cartridge helm [chart](https://github.com/tarantool/tarantool-operator/blob/fe1a588f2ecdacfb8f6a5833b1611011fdd8a6d5/examples/kv/helm-chart/templates/deployment.yaml#L117)

How to pass a value to the helm chart is clear - in `values.yaml`. Only one way.
How to unhardcode `cluster.local` in operator? Two ways:
- Get value from inside:
```go
func getClusterDomain(apiSvc string) string {
	cname, err := net.LookupCNAME(apiSvc)
	if err != nil {
		return "cluster.local"
	}
	return strings.Trim(strings.TrimPrefix(cname, apiSvc), ".")
}
```
- Pass value from the helm chart through the pod label.
```yaml
labels:
        tarantool.io/cluster-domain-name: "{{ $.Values.ClusterDomainName }}"
```
I consider it correct to use one source for this parameter.
If the user made a mistake and passed an incorrect `domain.name`, then the pods simply will not start.
However, if we receive the domain.name in the operator through `net.LookupCNAME`, a mismatch between the received value and the value passed by the user may occur. The mistake will not be easy to find.
