### ISSUE TITLE
Ready to use applications

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/tarantool-operator#39]
Tarantool CRUD and queue are pretty popular tarantool use cases. We could prepackage them into their own helm charts including dependencies (operator).

**Comment by vanyarock01** [comment]
#43

**Comment by vanyarock01** [comment]
In the `crud` chart, I used 2 dependencies (`tarantool-operator` and `cartridge` charts) to avoid code duplication, like [here](https://github.com/vasiliy-t/tarantool_examples/tree/master/crud-storage/helm-chart).
No new deployments in the chart - only dependencies.
The second way is not to create a new chart, but to add the `tarantool-operator` dependency to the `cartridge` chart. But you can't call it *ready-to-use*.
