### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/tarantool-operator#40]
We already have nice getting started in russian which includes complete developer walk through and several operations scenarios. We should

- [x]  translate it into english

- [ ] publish it on tarantool.io

**Comment by vanyarock01** [comment]
For posting to tarantool.io, I see several places:
- [Getting started page](https://www.tarantool.io/en/doc/latest/getting_started/), but Arthur says it's too early.
- [Cluster page](https://www.tarantool.io/en/doc/latest/book/cartridge/)
- [Tutorials page](https://www.tarantool.io/en/doc/latest/tutorials/)
- [Articles page](https://www.tarantool.io/en/learn/), but this page is hard to find and the last article came out 2 years ago. Is she even alive?
