### ISSUE TITLE
Leader switch 

### ISSUE THREAD

**Issue by vasiliy-t** [tarantool/tarantool-operator#6]
### Problem statement

Leader elected only once during cluster initial bootstrap

### Possible solution

1. Annotate Cluster resource with some field to denote tarantool cartridge cluster wide config generation

1. In case of leader failure cross check annotation with every instance config generation

1. select any alive instance with matching config generation as leader

**Comment by sastumpf** [comment]
Hi Dear Team! Is there any plans to fix the issue or recommendations to workaround it in order to automatically recover the cluster after the current leader failure?

**Comment by R-omk** [comment]
related https://github.com/tarantool/tarantool-operator/issues/71

**Comment by sharonovd** [comment]
Still valid?

**Comment by sastumpf** [comment]
Affirmative Sir. Clearing and reassembling the cluster manually quite regularly.

**Comment by R-omk** [comment]
There is no need to save the ip address because it can change after deleting the pod

**Comment by R-omk** [comment]
It need to choose a leader who has a non-empty disk after data loss. Otherwise, there will be a loss of the cluster config  (override with empty)  and a possible incorrect topology if we do not fix this issue https://github.com/tarantool/tarantool-operator/issues/116
