### ISSUE TITLE
Endpoint leader annotation update problem

### ISSUE THREAD

**Issue by robinhood23rus** [tarantool/tarantool-operator#77]
After recreating pods operator left endpoint annotation tarantool.io/leader unchanged with old IP address. So operator lost ability to manage cartridge configuration because of not existing node. 
In operator logs there are some errors about connection timeout while trying to connect to old IP.

**Comment by vanyarock01** [comment]
The operator saves the internal IP address of one of the pods and uses it to make admin requests.
But, for example, when you reinstall the service, the IP address may change. Then we get an error.

We need to use dns hostnames.
