### ISSUE TITLE
Require troubleshooting about cluster endpoints 

### ISSUE THREAD

**Issue by vanyarock01** [tarantool/tarantool-operator#95]
Why is this happening?

```
{"level":"info","ts":1617626612.6481433,"logger":"controller_cluster","msg":"No available Endpoint resource configured for Cluster, waiting","Request.Namespace":"tarantool","Request.Name":"xxxl"}
```

**Comment by chelsEg** [comment]
> Why is this happening?
> 
> ```
> {"level":"info","ts":1617626612.6481433,"logger":"controller_cluster","msg":"No available Endpoint resource configured for Cluster, waiting","Request.Namespace":"tarantool","Request.Name":"xxxl"}
> ```

How I can disable log trace or change level to error?

**Comment by patiencedaur** [comment]
@vasiliy-t is this a code error or just undocumented behavior?

**Comment by vasiliy-t** [comment]
This is not an error and there is no undocumented behaviour. This is part of normal operator lifecycle. May be we should change log level for this message to "verbose" or "debug" instead of "info"
